# Generated by Django 3.2.7 on 2021-09-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('price', models.PositiveIntegerField()),
                ('url', models.URLField()),
                ('time', models.CharField(max_length=128)),
                ('is_send', models.BooleanField(default=False)),
                ('external_id', models.BigIntegerField(unique=True)),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
